### ISSUE TITLE
Marquee Deprecated

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#1]
(example of MDN) Deprecated
This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/index.html#L16

as you work with marquee tag... DO NOT USE THIS. ap is k replace main animation use kr skti h. here is link
https://daneden.github.io/animate.css/
ap isko download kren then apny folder main rkhen aur index main isko link krwa den. for example apko para main animation chye to ap para main class put kr den jo b apko animation chye

**Comment by arifa-chouhdry** [comment]
#1 solved
