### ISSUE TITLE
Eye catch button

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#10]
JOIN NOW! it is an eye catch button, so as mockup, ap ko is ki padding increase krna chye. font size thora aur increase krna chye. and mockup ki trha font family b apply krna chye.

https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L53

**Comment by arifa-chouhdry** [comment]
#10 solved

**Comment by NoreenNaz1234** [comment]
font size abi b nh h same lkn phir b close  krrhi hn
