### ISSUE TITLE
Height required 

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#12]
https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L41

ap is section ko height den mock main ager ap dkhen to hide thori zada h. jab ap height increase krengi to apka content b disturb hoga to ap isko b handle krengi. second, height thori increase kiyjega

**Comment by arifa-chouhdry** [comment]
#12 solved

**Comment by NoreenNaz1234** [comment]
still height issue lkn ab ap is k responsive p focus kren
