### ISSUE TITLE
DO NOT USE MINUS margin

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#2]
https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L11

https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L39 

 please remove this from your code

**Comment by arifa-chouhdry** [comment]
#2 solved
