### ISSUE TITLE
Resize of LOGO

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#3]
https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L15
1st thing ap thora is ko margin den ta ke ye wall se touch na ho, second ap is ki height and widht set kren,, mockup main ager ap dkhen to tech karo ka text nazar arha h

**Comment by arifa-chouhdry** [comment]
#3 solved
