### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#4]
https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L19
ap ager mockup dkhen to nav bar blkul ap k navbar se different h.. ap li ka tag use na kren blke ap isko flex se set kren. like display: flex;   justify-content: space-between;
is trha apko itna css nh likhna parega

**Comment by arifa-chouhdry** [comment]
#4 solved
