### ISSUE TITLE
Repetition of Bg images 

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#5]
no need to repeat images again and again. ap just body main bg image den. and us k bad har section p rgba main bg-color den. rgba main color dena important h. as i told you reason before  
https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L40

**Comment by arifa-chouhdry** [comment]
#5 solved
