### ISSUE TITLE
Used margin a lot

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#7]
https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L47
 
mny apko phly b mana kia h k margin use na kren itna... isko margin ki need nh h blkul. ap simple isko text align se center kr skti h. please isko set kren.

**Comment by arifa-chouhdry** [comment]
#7 solved
