### ISSUE TITLE
About h1 or main heading 

### ISSUE THREAD

**Issue by NoreenNaz1234** [arifa-chouhdry/14-may-task#8]
https://github.com/arifa-chouhdry/14-may-task/blob/cd38806c0bcfd5d20dace5c1b3ca555bc0da92aa/style.css#L44

h1 is the main heading of your page.. ap ne mockup dkh k is ka font, font-family and font wieght set krna h. and top aur bottom main space den. means padding se set kren.

**Comment by arifa-chouhdry** [comment]
#8 solved
